# Generated by Django 3.2.5 on 2021-09-19 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App_user_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.CharField(max_length=50)),
                ('app_profile_pic', models.ImageField(default=None, null=True, upload_to='')),
                ('main_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_date', models.DateTimeField(auto_now_add=True)),
                ('casting', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('video_link', models.URLField(default='https://www.youtube.com/', null=True)),
                ('video_gif', models.ImageField(default=None, null=True, upload_to='upload/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netflix_app.video_category')),
            ],
        ),
        migrations.CreateModel(
            name='App_user_watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.app_user_account')),
                ('video_watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.video_data')),
            ],
        ),
        migrations.CreateModel(
            name='App_user_lastwatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.app_user_account')),
                ('video_watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.video_data')),
            ],
        ),
        migrations.CreateModel(
            name='App_user_favoritelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.app_user_account')),
                ('video_watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflix_app.video_data')),
            ],
        ),
    ]
